NAME = philo
CC = cc -g
CFLAGS  = -Wall -Wextra -Werror
CFILES =	erroc.c\
			moni.c\
			parsing_info.c\
			philo_utils.c\
			routine.c\
			set_up.c\
			main.c

LIBFT_D = ./libft
OFILES = $(SRC:.c=.o)

all : $(NAME)

$(NAME) : $(FILES)
	@